# General properties
server.port=${PORT:9090}
spring.main.allow-bean-definition-overriding=true

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#JWT auth
app.security.jwt.issuer=nike-ecommerce
app.security.jwt.access-tokem-ttl=PT30M
app.security.jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


