# Database connection
spring.datasource.url=jdbc:mysql://localhost:3307/nike_store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=trinhquocviet2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Logging
logging.level.org.springframework.security=DEBUG

# VNPay sandbox
payment.vnpay.tmn-code=EW05X2RA
payment.vnpay.hash-secret=9PF8L61HT11WKB53BH3JKYVTBTRSLN4B
payment.vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnpay.return-url=http://localhost:9090/api/payments/vnpay/return
payment.vnpay.ipn-url=http://localhost:9090/api/payments/vnpay/ipn
payment.vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# Admin product image local storage
app.storage.product-images.root-directory=uploads/products
