ALTER TABLE product_variants
    MODIFY COLUMN inventory_status VARCHAR(20) NULL DEFAULT 'IN_ORDER';

ALTER TABLE products
    MODIFY COLUMN product_status VARCHAR(20) NOT NULL;

ALTER TABLE users
    MODIFY COLUMN role VARCHAR(255) NOT NULL;

ALTER TABLE orders
    MODIFY COLUMN order_status VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT',
    MODIFY COLUMN shipping_method VARCHAR(15) NOT NULL DEFAULT 'STANDARD',
    MODIFY COLUMN payment_method VARCHAR(20) NOT NULL;
